version: '2'
services:
  db:
    build: ./
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DOCKER_USER: docker
      DOCKER_PASSWORD: docker
    ports:
      - '5432:5432'
